steps:
  - name: install
    entrypoint: yarn
    args: ["install"]
  - name: build
    entrypoint: yarn
    args: ["build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
